### ISSUE TITLE
I have segmentation fault everytime running your example, any way to fix ?

### ISSUE THREAD

**Issue by Snorfermino** [alexwasner/Wikitude-Swift#1]

**Comment by alexwasner** [comment]
Where exactly is it failing? Did you add your wikitude key and sdk

**Comment by Snorfermino** [comment]
i added wikitude key and SDK, run fine for the first time, after that it won't work, everytime i run on my IP5 error occur. My Iphone 5 is iOs 8.4.

**Comment by alexwasner** [comment]
@Snorfermino Can you provide some detailed errors?

**Comment by Snorfermino** [comment]
i managed to fix it. I tried to test on IP6 and ipad mini, it worked well, i don't know why ip5 got problem
